### ISSUE TITLE
Consider providing additional detail to the listing at the Umbraco marketplace

### ISSUE THREAD

**Issue by AndyButland** [abjerner/Limbo.Umbraco.BlockList#1]
Hi @abjerner - I noted you'd listed this package on the Umbraco marketplace, so firstly, thanks for taking the time to do that.  I noticed though that we only have the details collected from NuGet for the package... which is fine, but to help it to be found more easily it's possible to provide additional information, as is discussed [here](https://marketplace.umbraco.com/listing).

For example, you can add a category that the package will be shown under, and also provide additional descriptions or "read me" content to better describe what the package does and what benefits developers would get from installing it.

To use this you would need to first add a `ProjectUrl` to your `.cproj` file, which would then go into the NuGet package.

Then you can create a file in the folder of the project URL you are referencing, and populate it with the additional information in JSON format, as per the documentation linked above.

I won't spam you with issues but I believe the same applies to the following packages too:

- Limbo.Umbraco.Boolean
- Limbo.Umbraco.MultiNodeTreePicker
- Limbo.Umbraco.Rte
- Limbo.Umbraco.Separator

I hope the above is useful and thanks again for helping get the new website populated with the full range of extensions available to the Umbraco community.

**Comment by abjerner** [comment]
Fixed this a while ago for **Limbo.Umbraco.BlockList**, but left the issue open, as I needed to fix the other packages. I think they should all be updated now, so closing the issue.
